export const LOGIN_PAGE = '/'
export const FORGOTPASSWORD_PAGE = '/forgot-password'
export const  DASHBOARD_OVERVIEW = '/dashboard'
export const MEMBER_PAGE = '/dashboard/member-page'
export const EVENT_LISTE_PAGE = '/dashboard/event-page'
