import type { SponsorCategory, SponsorCategoryPagination } from "@/types/sponsorCategoriesTypes"

export interface SponsorCategoriesState {
  sponsorCategories: SponsorCategory[]
  all: SponsorCategory[]
  sponsorCategory: SponsorCategory | null
  count: number
  pagination: SponsorCategoryPagination | null
  isLoading: boolean
  isLoadingAll: boolean
  isCreating: boolean
  isUpdating: boolean
  isDeleted: boolean
  error: string | null
}

export const FETCH_SPONSOR_CATEGORIES_REQUEST = 'FETCH_SPONSOR_CATEGORIES_REQUEST'
export const FETCH_SPONSOR_CATEGORIES_SUCCESS = 'FETCH_SPONSOR_CATEGORIES_SUCCESS'
export const FETCH_SPONSOR_CATEGORIES_FAILURE = 'FETCH_SPONSOR_CATEGORIES_FAILURE'

export const FETCH_ALL_SPONSOR_CATEGORIES_REQUEST = 'FETCH_ALL_SPONSOR_CATEGORIES_REQUEST'
export const FETCH_ALL_SPONSOR_CATEGORIES_SUCCESS = 'FETCH_ALL_SPONSOR_CATEGORIES_SUCCESS'
export const FETCH_ALL_SPONSOR_CATEGORIES_FAILURE = 'FETCH_ALL_SPONSOR_CATEGORIES_FAILURE'

export const FETCH_SPONSOR_CATEGORY_BY_ID_REQUEST = 'FETCH_SPONSOR_CATEGORY_BY_ID_REQUEST'
export const FETCH_SPONSOR_CATEGORY_BY_ID_SUCCESS = 'FETCH_SPONSOR_CATEGORY_BY_ID_SUCCESS'
export const FETCH_SPONSOR_CATEGORY_BY_ID_FAILURE = 'FETCH_SPONSOR_CATEGORY_BY_ID_FAILURE'

export const CREATE_SPONSOR_CATEGORY_REQUEST = 'CREATE_SPONSOR_CATEGORY_REQUEST'
export const CREATE_SPONSOR_CATEGORY_SUCCESS = 'CREATE_SPONSOR_CATEGORY_SUCCESS'
export const CREATE_SPONSOR_CATEGORY_FAILURE = 'CREATE_SPONSOR_CATEGORY_FAILURE'

export const UPDATE_SPONSOR_CATEGORY_REQUEST = 'UPDATE_SPONSOR_CATEGORY_REQUEST'
export const UPDATE_SPONSOR_CATEGORY_SUCCESS = 'UPDATE_SPONSOR_CATEGORY_SUCCESS'
export const UPDATE_SPONSOR_CATEGORY_FAILURE = 'UPDATE_SPONSOR_CATEGORY_FAILURE'

export const DELETE_SPONSOR_CATEGORY_REQUEST = 'DELETE_SPONSOR_CATEGORY_REQUEST'
export const DELETE_SPONSOR_CATEGORY_SUCCESS = 'DELETE_SPONSOR_CATEGORY_SUCCESS'
export const DELETE_SPONSOR_CATEGORY_FAILURE = 'DELETE_SPONSOR_CATEGORY_FAILURE'
